trigger:
- beta

strategy:
  matrix:
    mac:
      imageName: 'macos-10.14'
    #linux:
    #  imageName: 'ubuntu-16.04'

pool:
  vmImage: $(imageName)

steps:
  - bash: |
      brew update
      brew upgrade
      brew tap discoteq/discoteq; brew install flock
      brew install autoconf autogen automake
      brew update && brew install gcc@8
      brew install binutils
      brew install protobuf
      brew install coreutils
      brew install wget
    displayName: 'Do the brew magic'
  - bash: |
     git clone https://github.com/komodoplatform/komodo --branch beta --single-branch
     cd komodo
     ./zcutil/fetch-params.sh
     ./zcutil/build-mac.sh -j$(sysctl -n hw.ncpu)
    displayName: 'Compile Komodo'
