trigger:
- beta

strategy:
  matrix:
    mac:
      imageName: 'macos-10.13'
    #linux:
    #  imageName: 'ubuntu-16.04'
    
pool:
  vmImage: $(imageName)

steps:
  - displayName: 'Do the brew magic'
    bash: |
      brew update
      brew upgrade
      brew tap discoteq/discoteq; brew install flock
      brew install autoconf autogen automake
      brew update && brew install gcc@8
      brew install binutils
      brew install protobuf
      brew install coreutils
      brew install wget
# - displayName: 'Compile Komodo'
#   bash: |
#     # Clone the Komodo repo
#     git clone https://github.com/komodoplatform/komodo --branch master --single-branch
#     # Change master branch to other branch you wish to compile
#     cd komodo
#     ./zcutil/fetch-params.sh
#     # -j8 = using 8 threads for the compilation - replace 8 with number of threads you want to use
#     ./zcutil/build-mac.sh -j8