# File: .github/workflows/repo-sync.yml
name: Source Repo Sync

on:
  schedule:
  - cron:  "0 0 * * 0"

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: reposync
      uses: ns408/github_actions_reposync@master
      with:
        source_repo: "jl777/komodo"
        source_branch: "dev"
        destination_branch: "dev"
        github_token: ${{ secrets.meshbits_repo_sync }}
